<script lang="ts">
  import type { PageProps } from './$types'
  import StatsImport from '$lib/components/admin/StatsImport.svelte'
  import CustomSelect from '$lib/components/CustomSelect.svelte'
  import { Loader2, RefreshCw, Save, Trash2, Wand2 } from 'lucide-svelte'
  import { MATCH_STAGES, SECTIONS, resolveBatchSection, sectionLabel } from '$lib/stats/sections'

  let { data }: PageProps = $props()

  const batches = $derived(data.batches ?? [])
  const seasons = $derived(data.seasons ?? [])

  // A season is required: an unscoped batch sweeps up every season at once.
  const seasonOptions = $derived([
    { value: '', label: 'Pick a season…' },
    ...seasons.map((s) => ({
      value: s.id,
      label: `${s.name ?? s.code ?? s.id.slice(0, 8)}${s.is_active ? ' (active)' : ''}`,
    })),
  ])

  const sectionOptions = [
    { value: '', label: 'Auto (from name)' },
    ...SECTIONS.map((s) => ({ value: s.key, label: s.label })),
  ]

  // ---------------------------------------------------------------- generate

  /**
   * A batch is generated by scoping matches, not by uploading anything: pick a
   * season, tick the stages, and every imported match filed under them is
   * aggregated into one batch.
   *
   * Left live (the default) the batch is a standing subscription rather than a
   * snapshot — set up "Season 5 Kickoff" before a single match exists and every
   * import in that scope refills it. The stage counts come back from the API so
   * the scope is visible before it runs, and they only count matches carrying
   * advanced stats, which is exactly what a generated batch can use.
   */
  let genSeasonId = $state('')
  let genStages = $state<Record<string, boolean>>({})
  let genName = $state('')
  let genNameTouched = $state(false)
  let genSection = $state('')
  let genSortOrder = $state('')
  let genAutoRefresh = $state(true)
  let generating = $state(false)
  let genMessage = $state<{ ok: boolean; text: string } | null>(null)
  let stageCounts = $state<Record<string, number>>({})
  let countsLoading = $state(false)

  const selectedStages = $derived(MATCH_STAGES.filter((s) => genStages[s.key]).map((s) => s.key))

  const inScopeCount = $derived(
    selectedStages.length === 0
      ? Object.entries(stageCounts).reduce((total, [, n]) => total + n, 0)
      : selectedStages.reduce((total, key) => total + (stageCounts[key] ?? 0), 0)
  )

  /** "Season 5 — Playoffs" writes itself until the admin types their own name. */
  const suggestedName = $derived.by(() => {
    const season = seasons.find((s) => s.id === genSeasonId)
    const seasonPart = season ? (season.name ?? season.code ?? '') : ''
    const stagePart =
      selectedStages.length === 1
        ? sectionLabel(selectedStages[0])
        : selectedStages.length > 1
          ? selectedStages.map((k) => sectionLabel(k)).join(' + ')
          : ''
    return [seasonPart, stagePart].filter(Boolean).join(' — ')
  })

  $effect(() => {
    const next = suggestedName
    if (!genNameTouched) genName = next
  })

  $effect(() => {
    const seasonId = genSeasonId
    if (!seasonId) {
      stageCounts = {}
      return
    }
    countsLoading = true
    const url = `/api/admin/stats/generate?seasonId=${encodeURIComponent(seasonId)}`
    window
      .fetch(url)
      .then((res) => res.json())
      .then((body) => {
        stageCounts = (body?.countsByStage ?? {}) as Record<string, number>
      })
      .catch(() => {
        stageCounts = {}
      })
      .finally(() => {
        countsLoading = false
      })
  })

  async function generate() {
    generating = true
    genMessage = null
    try {
      const res = await window.fetch('/api/admin/stats/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'generate',
          seasonId: genSeasonId || null,
          stages: selectedStages,
          displayName: genName,
          section: genSection || null,
          sortOrder: genSortOrder,
          autoRefresh: genAutoRefresh,
        }),
      })
      const body = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(body?.message ?? 'Failed to generate batch')
      genMessage = {
        ok: true,
        text:
          body.matchCount === 0
            ? `Created "${genName}" — empty for now, it will fill as matches in that scope are imported.`
            : `Generated "${genName}" — ${body.playerCount} players across ${body.matchCount} matches.`,
      }
      window.setTimeout(() => window.location.reload(), 1600)
    } catch (err) {
      genMessage = { ok: false, text: err instanceof Error ? err.message : 'Failed to generate' }
    } finally {
      generating = false
    }
  }

  // ------------------------------------------------------------- batch table

  let orderById = $state<Record<string, string>>({})
  let sectionById = $state<Record<string, string>>({})
  let liveById = $state<Record<string, boolean>>({})
  let savingId = $state<string | null>(null)
  let regeneratingId = $state<string | null>(null)
  let deletingId = $state<string | null>(null)
  let message = $state<string | null>(null)

  $effect(() => {
    const nextOrder: Record<string, string> = {}
    const nextSection: Record<string, string> = {}
    const nextLive: Record<string, boolean> = {}
    for (const b of batches) {
      nextOrder[b.id] =
        b.sort_order === null || b.sort_order === undefined ? '' : String(b.sort_order)
      nextSection[b.id] = b.section ?? ''
      nextLive[b.id] = Boolean(b.auto_refresh)
    }
    orderById = nextOrder
    sectionById = nextSection
    liveById = nextLive
  })

  async function saveBatch(batchId: string, generated: boolean) {
    savingId = batchId
    message = null
    try {
      const res = await window.fetch(`/api/admin/stats/batches/${batchId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sortOrder: orderById[batchId] ?? '',
          section: sectionById[batchId] ?? '',
          // Only generated batches have anything to refresh from.
          ...(generated ? { autoRefresh: Boolean(liveById[batchId]) } : {}),
        }),
      })
      const body = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(body?.message ?? 'Failed to save batch')
      message = 'Saved.'
      window.location.reload()
    } catch (err) {
      message = err instanceof Error ? err.message : 'Failed to save batch'
    } finally {
      savingId = null
    }
  }

  async function deleteBatch(batchId: string, label: string) {
    if (
      !window.confirm(
        `Delete "${label}" and every stat row in it? This cannot be undone, and any link pointing at this batch will break.`
      )
    ) {
      return
    }
    deletingId = batchId
    message = null
    try {
      const res = await window.fetch(`/api/admin/stats/batches/${batchId}`, { method: 'DELETE' })
      const body = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(body?.message ?? 'Failed to delete batch')
      message = `Deleted "${label}".`
      window.location.reload()
    } catch (err) {
      message = err instanceof Error ? err.message : 'Failed to delete batch'
    } finally {
      deletingId = null
    }
  }

  async function regenerate(batchId: string) {
    regeneratingId = batchId
    message = null
    try {
      const res = await window.fetch('/api/admin/stats/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'regenerate', batchId }),
      })
      const body = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(body?.message ?? 'Failed to regenerate batch')
      message = `Rebuilt from ${body.matchCount} matches (${body.playerCount} players).`
    } catch (err) {
      message = err instanceof Error ? err.message : 'Failed to regenerate batch'
    } finally {
      regeneratingId = null
    }
  }

  function shortId(id: string) {
    return id.slice(0, 8)
  }
</script>

<StatsImport {data} />

<div class="flex justify-center px-4 pb-10">
  <div class="w-full max-w-6xl">
    <section class="admin-card admin-card-pad mt-6">
      <div class="admin-section-title">Generate From Imported Matches</div>
      <div class="admin-hint mt-1">
        Aggregates matches imported from tracker links into a single batch, scoped to one season and
        its stages. A match's stage comes from the Stage field on the match; matches without one are
        guessed from their designation ("Grand Finals", "Week 3") and otherwise counted as unfiled.
        Hand-entered matches never appear here — only imports carry the advanced stats a generated
        batch is built from.
      </div>
      <div class="admin-hint mt-1">
        Left live, the batch is a standing rule rather than a snapshot: set up "Season 5 Kickoff"
        before the event and every import in that scope refills it automatically.
      </div>

      <div class="mt-4 grid gap-4 md:grid-cols-2">
        <label class="text-xs" style="color: rgba(255,255,255,0.82);">
          Season
          <div class="mt-1">
            <CustomSelect
              options={seasonOptions}
              value={genSeasonId}
              compact={true}
              onSelect={(value) => (genSeasonId = value)}
            />
          </div>
        </label>

        <label class="text-xs" style="color: rgba(255,255,255,0.82);">
          Section in the stats picker
          <div class="mt-1">
            <CustomSelect
              options={sectionOptions}
              value={genSection}
              compact={true}
              onSelect={(value) => (genSection = value)}
            />
          </div>
          <span class="admin-hint mt-1 block">
            Leave on Auto when one stage is ticked — the batch is filed under it.
          </span>
        </label>
      </div>

      <div class="mt-4">
        <div class="text-xs" style="color: rgba(255,255,255,0.82);">
          Stages {countsLoading ? '(counting…)' : ''}
        </div>
        <div class="mt-2 flex flex-wrap gap-2">
          {#each MATCH_STAGES as stage (stage.key)}
            <button
              type="button"
              class="stage-chip"
              class:stage-on={genStages[stage.key]}
              disabled={!genSeasonId}
              onclick={() => (genStages = { ...genStages, [stage.key]: !genStages[stage.key] })}
            >
              {stage.label}
              <span class="stage-count">{stageCounts[stage.key] ?? 0}</span>
            </button>
          {/each}
          {#if (stageCounts.unfiled ?? 0) > 0}
            <span class="stage-chip stage-muted">
              Unfiled
              <span class="stage-count">{stageCounts.unfiled}</span>
            </span>
          {/if}
        </div>
        <div class="admin-hint mt-2">
          {#if !genSeasonId}
            Pick a season to see what is in scope.
          {:else if selectedStages.length === 0}
            No stage ticked — every imported match in the season is included ({inScopeCount} so far, unfiled
            ones too).
          {:else if inScopeCount === 0}
            Nothing imported for those stages yet — a live batch will fill itself in as matches
            arrive.
          {:else}
            {inScopeCount} imported {inScopeCount === 1 ? 'match' : 'matches'} in scope.
          {/if}
        </div>
      </div>

      <label class="mt-4 flex items-start gap-2 text-xs" style="color: rgba(255,255,255,0.82);">
        <input type="checkbox" class="mt-0.5" bind:checked={genAutoRefresh} />
        <span>
          Keep this batch up to date
          <span class="admin-hint mt-0.5 block">
            Rebuilds itself whenever a match in this scope is imported. Turn off for a frozen
            snapshot of what exists right now.
          </span>
        </span>
      </label>

      <div class="mt-4 grid gap-4 md:grid-cols-3">
        <label class="text-xs md:col-span-2" style="color: rgba(255,255,255,0.82);">
          Batch name
          <input
            class="admin-input mt-1"
            value={genName}
            placeholder="e.g. Season 5 — Playoffs"
            oninput={(e) => {
              genNameTouched = true
              genName = (e.currentTarget as HTMLInputElement).value
            }}
          />
        </label>
        <label class="text-xs" style="color: rgba(255,255,255,0.82);">
          Order (optional)
          <input class="admin-input mt-1" placeholder="(auto)" bind:value={genSortOrder} />
        </label>
      </div>

      <div class="mt-4 flex items-center gap-3">
        <button
          type="button"
          class="admin-btn admin-btn-info"
          onclick={generate}
          disabled={generating ||
            !genName.trim() ||
            !genSeasonId ||
            (inScopeCount === 0 && !genAutoRefresh)}
        >
          {#if generating}
            <Loader2 size={14} class="animate-spin" />
            Generating...
          {:else}
            <Wand2 size={14} />
            {inScopeCount === 0 ? 'Create live batch' : 'Generate batch'}
          {/if}
        </button>
        {#if genMessage}
          <span
            class="text-sm"
            style="color: {genMessage.ok ? 'rgba(134,239,172,0.95)' : 'rgba(252,165,165,0.95)'};"
          >
            {genMessage.text}
          </span>
        {/if}
      </div>
    </section>

    <section class="admin-card admin-card-pad mt-6">
      <div class="admin-section-title">Batch Sections &amp; Ordering</div>
      <div class="admin-hint mt-1">
        Section groups the batch in the stats picker. Auto reads it from the batch name, which is
        how existing imports are filed — set it explicitly when the name does not say. Order is a
        number within the whole list; lower appears first, blank falls back to the default. Live
        batches rebuild themselves on every covered match import; empty ones stay hidden from the
        public picker until they have rows.
      </div>

      {#if message}
        <div class="mt-3 text-sm" style="color: rgba(255,255,255,0.85);">{message}</div>
      {/if}

      <div class="table-scroll mt-4">
        <table class="min-w-full text-left text-sm">
          <thead>
            <tr class="text-xs tracking-wide uppercase" style="color: rgba(255,255,255,0.75);">
              <th class="px-3 py-2">Order</th>
              <th class="px-3 py-2">Name</th>
              <th class="px-3 py-2">Section</th>
              <th class="px-3 py-2">Kind</th>
              <th class="px-3 py-2">Week</th>
              <th class="px-3 py-2">Created</th>
              <th class="px-3 py-2">ID</th>
              <th class="px-3 py-2">Actions</th>
            </tr>
          </thead>
          <tbody>
            {#each batches as b (b.id)}
              <tr class="admin-divide border-t">
                <td class="px-3 py-2">
                  <input
                    class="admin-input w-20"
                    placeholder="(auto)"
                    bind:value={orderById[b.id]}
                  />
                </td>
                <td class="px-3 py-2" style="color: rgba(255,255,255,0.9);">
                  {b.display_name}
                  {#if b.auto_refresh}
                    <span class="batch-tag tag-live">live</span>
                  {:else if b.generated}
                    <span class="batch-tag">generated</span>
                  {/if}
                  {#if b.row_count === 0}
                    <span class="batch-tag">empty — hidden</span>
                  {/if}
                </td>
                <td class="px-3 py-2" style="min-width: 11rem;">
                  <CustomSelect
                    options={sectionOptions}
                    value={sectionById[b.id] ?? ''}
                    compact={true}
                    onSelect={(value) => (sectionById = { ...sectionById, [b.id]: value })}
                  />
                  {#if !sectionById[b.id]}
                    <span class="admin-hint mt-1 block"
                      >→ {sectionLabel(resolveBatchSection(b))}</span
                    >
                  {/if}
                </td>
                <td class="px-3 py-2" style="color: rgba(255,255,255,0.8);"
                  >{b.import_kind ?? '—'}</td
                >
                <td class="px-3 py-2" style="color: rgba(255,255,255,0.8);"
                  >{b.week_label ?? '—'}</td
                >
                <td class="px-3 py-2" style="color: rgba(255,255,255,0.8);">
                  {b.created_at
                    ? new Date(b.created_at).toLocaleString(undefined, { timeZone: 'UTC' })
                    : '—'}
                </td>
                <td
                  class="px-3 py-2"
                  style="color: rgba(255,255,255,0.75); font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;"
                >
                  {shortId(b.id)}
                </td>
                <td class="px-3 py-2">
                  {#if b.generated}
                    <label class="mb-2 flex items-center gap-1.5 text-xs whitespace-nowrap">
                      <input
                        type="checkbox"
                        checked={liveById[b.id] ?? false}
                        onchange={(e) =>
                          (liveById = {
                            ...liveById,
                            [b.id]: (e.currentTarget as HTMLInputElement).checked,
                          })}
                      />
                      Keep updated
                    </label>
                  {/if}
                  <div class="flex flex-wrap gap-2">
                    <button
                      type="button"
                      class="admin-btn admin-btn-sm admin-btn-info"
                      onclick={() => saveBatch(b.id, Boolean(b.generated))}
                      disabled={savingId === b.id}
                    >
                      <Save size={14} />
                      {savingId === b.id ? 'Saving...' : 'Save'}
                    </button>
                    {#if b.generated}
                      <button
                        type="button"
                        class="admin-btn admin-btn-sm"
                        title="Rebuild this batch from its source matches, keeping the same id"
                        onclick={() => regenerate(b.id)}
                        disabled={regeneratingId === b.id}
                      >
                        <RefreshCw size={14} />
                        {regeneratingId === b.id ? 'Rebuilding...' : 'Regenerate'}
                      </button>
                    {/if}
                    <button
                      type="button"
                      class="admin-btn admin-btn-sm admin-btn-danger"
                      title="Delete this batch and every stat row in it"
                      onclick={() => deleteBatch(b.id, b.display_name)}
                      disabled={deletingId === b.id}
                    >
                      <Trash2 size={14} />
                      {deletingId === b.id ? 'Deleting...' : 'Delete'}
                    </button>
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </section>
  </div>
</div>

<style>
  .stage-chip {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    padding: 0.3rem 0.6rem;
    font-size: 0.8125rem;
    border-radius: 999px;
    border: 1px solid var(--border);
    background-color: rgba(0, 0, 0, 0.3);
    color: rgba(255, 255, 255, 0.85);
    cursor: pointer;
    transition:
      border-color 0.15s ease,
      background-color 0.15s ease;
  }

  .stage-chip:hover {
    border-color: var(--accent);
  }

  .stage-chip.stage-on {
    background-color: var(--accent);
    border-color: var(--accent);
    color: #fff;
  }

  .stage-chip.stage-muted {
    cursor: default;
    opacity: 0.6;
  }

  .stage-chip:disabled {
    cursor: not-allowed;
    opacity: 0.45;
  }

  .stage-chip:disabled:hover {
    border-color: var(--border);
  }

  .stage-count {
    font-variant-numeric: tabular-nums;
    font-size: 0.75rem;
    opacity: 0.8;
  }

  .batch-tag {
    display: inline-block;
    margin-left: 0.4rem;
    padding: 0.05rem 0.35rem;
    font-size: 0.6875rem;
    white-space: nowrap;
    border-radius: 0.25rem;
    border: 1px solid var(--border);
    color: rgba(255, 255, 255, 0.6);
  }

  .batch-tag.tag-live {
    border-color: rgba(134, 239, 172, 0.5);
    color: rgba(134, 239, 172, 0.95);
  }
</style>
